Newssite/sitenews/news/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', about, name='about'),
    path('addpage/', AddPage.as_view(), name='addpage'),
    path('contact/', contact, name='contact'),
    path('login/', login, name='login'),
    path('post/<slug:slug>/', GetPost.as_view(), name='post'),
    path('search/', Search.as_view(), name='search'),
    path('category/<slug:slug>/', PostsByCategory.as_view(), name='category'),
    path('tag/<slug:slug>/', PostsByTag.as_view(), name='tag'),
]

Newssite/sitenews/sitenews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from news.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('news.urls')),
    path('users/', include('users.urls', namespace="users")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = "Панель администратора"
admin.site.index_title = "Администратор новостного сайта"

Newssite/sitenews/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from .views import *


app_name = "users"

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
        template_name="users/password_reset.html",
        email_template_name="users/password_reset_email.html",
        success_url=reverse_lazy("users:password_reset_done")
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        success_url=reverse_lazy("users:password_reset_complete")
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

Newssite/sitenews/users/models.py
from django.db import models

# Create your models here.

Newssite/sitenews/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from captcha.fields import CaptchaField


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="Login | E-mail: ", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Password: ", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField(label="Captcha: ")

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Login", widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Name',
            'last_name': 'Surname',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('This e-mail already exists')
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label="Login", widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(disabled=True, label="E-mail", widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Name',
            'last_name': 'Surname',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Old Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(label="New Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(label="Confirm New Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

Newssite/sitenews/users/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Login'}


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Registration'}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'User Profile'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change.html'
    extra_context = {'title': 'Change Password'}

Newssite/sitenews/users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}

{{ title }} - {{ block.super }}

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mt-3">
                            <h4 class="m-0 text-uppercase font-weight-bold">{{ title }}</h4>
                        </div>
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="form-error">{{ form.non_field_errors }}</div>
                            {% for f in form %}
                            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}
                            </p>
                            <div class="form-error">{{ f.errors }}</div>
                            {% endfor %}
                        </div>
                        <button class="btn btn-primary font-weight-semi-bold px-4"
                                style="height: 50px; margin-bottom: 5px" type="submit">Enter</button>
                    </form>

                    <a href="{% url 'users:password_reset' %}"><button class="btn btn-primary font-weight-semi-bold px-4"
                                style="height: 50px; position: absolute; bottom: 5px; right: 16px;" type="submit">Forgot Password</button></a>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Newssite/sitenews/users/templates/users/password_change.html
{% extends 'base.html' %}

{% block title %}

{{ title }} - {{ block.super }}

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mt-3">
                            <h4 class="m-0 text-uppercase font-weight-bold">{{ title }}</h4>
                        </div>
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="form-error">{{ form.non_field_errors }}</div>
                            {% for f in form %}
                            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}
                            </p>
                            <div class="form-error">{{ f.errors }}</div>
                            {% endfor %}
                        </div>
                        <button class="btn btn-primary font-weight-semi-bold px-4"
                                style="height: 50px; margin-bottom: 5px" type="submit">Set New Password</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Newssite/sitenews/users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load static %}

{% block title %}

{{ title }} - {{ block.super }}

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mt-3">
                            <h4 class="m-0 text-uppercase font-weight-bold">You have successfully changed your password.
                                <a href="{% url 'users:profile' %}">Return to Profile</a>.</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Newssite/sitenews/users/templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %}

{{ title }} - {{ block.super }}

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mt-3">
                            <h4 class="m-0 text-uppercase font-weight-bold">{{ title }}</h4>
                        </div>
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="form-error">{{ form.non_field_errors }}</div>
                            {% for f in form %}
                            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}
                            </p>
                            <div class="form-error">{{ f.errors }}</div>
                            {% endfor %}
                        </div>
                        <button class="btn btn-primary font-weight-semi-bold px-4"
                                style="height: 50px; margin-bottom: 5px" type="submit">Reset by E-mail</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Newssite/sitenews/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}

{{ title }} - {{ block.super }}

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mt-3">
                            <h4 class="m-0 text-uppercase font-weight-bold">Congratulations, you have successfully changed your Password,
                                <a href="{% url 'users:profile' %}">use it to Login</a>.</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Newssite/sitenews/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}

{{ title }} - {{ block.super }}

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mt-3">
                            <h4 class="m-0 text-uppercase font-weight-bold">{{ title }}</h4>
                        </div>
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="form-error">{{ form.non_field_errors }}</div>
                            {% for f in form %}
                            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}
                            </p>
                            <div class="form-error">{{ f.errors }}</div>
                            {% endfor %}
                        </div>
                        <button class="btn btn-primary font-weight-semi-bold px-4"
                                style="height: 50px; margin-bottom: 5px" type="submit">Save</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Newssite/sitenews/users/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %}

{{ title }} - {{ block.super }}

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mt-3">
                            <h4 class="m-0 text-uppercase font-weight-bold">
                                We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

                                If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Newssite/sitenews/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

Newssite/sitenews/users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}

{{ title }} - {{ block.super }}

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mt-3">
                            <h4 class="m-0 text-uppercase font-weight-bold">{{ title }}</h4>
                        </div>
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="form-error">{{ form.non_field_errors }}</div>
                            {% for f in form %}
                            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}
                            </p>
                            <div class="form-error">{{ f.errors }}</div>
                            {% endfor %}
                        </div>
                        <button class="btn btn-primary font-weight-semi-bold px-4"
                                style="height: 50px; margin-bottom: 5px" type="submit">Save</button>
                    </form>

                    <a href="{% url 'users:password_change' %}"><button class="btn btn-primary font-weight-semi-bold px-4"
                                style="height: 50px; position: absolute; bottom: 5px; right: 16px;" type="submit">Change Password</button></a>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Newssite/sitenews/users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}

{{ title }} - {{ block.super }}

{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-lg">
                <div class="row">
                    <div class="col-12">
                        <div class="section-title mt-3">
                            <h4 class="m-0 text-uppercase font-weight-bold">{{ title }}</h4>
                        </div>
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="form-error">{{ form.non_field_errors }}</div>
                            {% for f in form %}
                            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}
                            </p>
                            <div class="form-error">{{ f.errors }}</div>
                            {% endfor %}
                        </div>
                        <button class="btn btn-primary font-weight-semi-bold px-4"
                                style="height: 50px; margin-bottom: 5px" type="submit">Registration</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}