Newssite/sitenews/news/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', about, name='about'),
    path('addpage/', AddPage.as_view(), name='addpage'),
    path('contact/', contact, name='contact'),
    path('login/', login, name='login'),
    path('post/<slug:slug>/', GetPost.as_view(), name='post'),
    path('search/', Search.as_view(), name='search'),
    path('category/<slug:slug>/', PostsByCategory.as_view(), name='category'),
    path('tag/<slug:slug>/', PostsByTag.as_view(), name='tag'),
]

Newssite/sitenews/sitenews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from news.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('', include('news.urls')),
    path('users/', include('users.urls', namespace="users")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = "Панель администратора"
admin.site.index_title = "Администратор новостного сайта"

Newssite/sitenews/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from .views import *


app_name = "users"

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
        template_name="users/password_reset.html",
        email_template_name="users/password_reset_email.html",
        success_url=reverse_lazy("users:password_reset_done")
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        success_url=reverse_lazy("users:password_reset_complete")
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

Newssite/sitenews/templates/include/_footer.html
{% load static %}
<!-- Footer Start -->

<!--<div class="container-fluid bg-dark pt-5 px-sm-3 px-md-5 mt-5">-->
<!--    <div class="row py-4">-->
<!--        <div class="col-lg-3 col-md-6 mb-5">-->
<!--            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Get In Touch</h5>-->
<!--            <p class="font-weight-medium"><i class="fa fa-map-marker-alt mr-2"></i>123 Street, New York, USA</p>-->
<!--            <p class="font-weight-medium"><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p>-->
<!--            <p class="font-weight-medium"><i class="fa fa-envelope mr-2"></i>info@example.com</p>-->
<!--            <h6 class="mt-4 mb-3 text-white text-uppercase font-weight-bold">Follow Us</h6>-->
<!--            <div class="d-flex justify-content-start">-->
<!--                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" href="#"><i class="fab fa-twitter"></i></a>-->
<!--                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>-->
<!--                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>-->
<!--                <a class="btn btn-lg btn-secondary btn-lg-square mr-2" href="#"><i class="fab fa-instagram"></i></a>-->
<!--                <a class="btn btn-lg btn-secondary btn-lg-square" href="#"><i class="fab fa-youtube"></i></a>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="col-lg-3 col-md-6 mb-5">-->
<!--            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Popular News</h5>-->
<!--            <div class="mb-3">-->
<!--                <div class="mb-2">-->
<!--                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="">Business</a>-->
<!--                    <a class="text-body" href=""><small>Jan 01, 2045</small></a>-->
<!--                </div>-->
<!--                <a class="small text-body text-uppercase font-weight-medium" href="">Lorem ipsum dolor sit amet elit. Proin vitae porta diam...</a>-->
<!--            </div>-->
<!--            <div class="mb-3">-->
<!--                <div class="mb-2">-->
<!--                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="">Business</a>-->
<!--                    <a class="text-body" href=""><small>Jan 01, 2045</small></a>-->
<!--                </div>-->
<!--                <a class="small text-body text-uppercase font-weight-medium" href="">Lorem ipsum dolor sit amet elit. Proin vitae porta diam...</a>-->
<!--            </div>-->
<!--            <div class="">-->
<!--                <div class="mb-2">-->
<!--                    <a class="badge badge-primary text-uppercase font-weight-semi-bold p-1 mr-2" href="">Business</a>-->
<!--                    <a class="text-body" href=""><small>Jan 01, 2045</small></a>-->
<!--                </div>-->
<!--                <a class="small text-body text-uppercase font-weight-medium" href="">Lorem ipsum dolor sit amet elit. Proin vitae porta diam...</a>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="col-lg-3 col-md-6 mb-5">-->
<!--            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Categories</h5>-->
<!--            <div class="m-n1">-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Politics</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Business</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Corporate</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Business</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Health</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Education</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Science</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Business</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Foods</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Entertainment</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Travel</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Lifestyle</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Politics</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Business</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Corporate</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Business</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Health</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Education</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Science</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Business</a>-->
<!--                <a href="" class="btn btn-sm btn-secondary m-1">Foods</a>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="col-lg-3 col-md-6 mb-5">-->
<!--            <h5 class="mb-4 text-white text-uppercase font-weight-bold">Flickr Photos</h5>-->
<!--            <div class="row">-->
<!--                <div class="col-4 mb-3">-->
<!--                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-1.jpg' %}" alt=""></a>-->
<!--                </div>-->
<!--                <div class="col-4 mb-3">-->
<!--                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-2.jpg' %}" alt=""></a>-->
<!--                </div>-->
<!--                <div class="col-4 mb-3">-->
<!--                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-3.jpg' %}" alt=""></a>-->
<!--                </div>-->
<!--                <div class="col-4 mb-3">-->
<!--                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-4.jpg' %}" alt=""></a>-->
<!--                </div>-->
<!--                <div class="col-4 mb-3">-->
<!--                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-5.jpg' %}" alt=""></a>-->
<!--                </div>-->
<!--                <div class="col-4 mb-3">-->
<!--                    <a href=""><img class="w-100" src="{% static 'img/news-110x110-1.jpg' %}" alt=""></a>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<div class="container-fluid py-4 px-sm-3 px-md-5" style="background: #111111;">
    <p class="m-0 text-center">&copy; <a href="{% url 'home' %}">Site News</a>.
        All Rights Reserved. Design by <a href="https://getbootstrap.com/docs/5.3/getting-started/introduction/">Bootstrap</a></p>
</div>

<!-- Footer End -->

Newssite/sitenews/templates/include/_header.html
{% load static %}
{% load category_menu %}

<!-- Navbar Start -->

<div class="container-fluid p-0">
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-2 py-lg-0 px-lg-5">
        <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
            <div class="navbar-nav mr-auto py-0">
                <a href="{% url 'home' %}" class="nav-item nav-link active">Home</a>
                <a href="{% url 'about' %}" class="nav-item nav-link">About</a>
                <a href="{% url 'addpage' %}" class="nav-item nav-link">Addpage</a>
                <a href="{% url 'contact' %}" class="nav-item nav-link">Contact</a>
                {% show_category_menu %}
            </div>

            <div class="input-group ml-auto d-none d-lg-flex" style="width: 100%; max-width: 500px;">
                <form action="{% url 'search' %}" method="get">
                    <div class="input-group-append">
                        <input type="text" name="search" class="form-control border-0" placeholder="Search">
                        <button class="input-group-text bg-primary text-dark border-0 px-3" type="submit">
                            <i class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>

            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'users:profile' %}">Welcome {{ user.username }}<a href="{% url 'users:logout' %}" class="nav-item nav-link">Exit</a></a>
                {% else %}
                    <a><a href="{% url 'users:login' %}" class="nav-item nav-link">Login</a><a href="{% url 'users:register' %}" class="nav-item nav-link">Registration</a></a>
                {% endif %}
            </div>
        </div>
    </nav>
</div>

<!-- Navbar End -->